import s from "./terms.module.css";

export default function Terms() {
  return (
    <div className={s.page}>
      <div className={s.container}>
        <h1>Terms of Service</h1>
        <p className={s.updated}>Last updated: March 25, 2026</p>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing or using ArmIQ AI (&quot;Service&quot;), operated by HIT24 (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>

        <h2>2. Description of Service</h2>
        <p>ArmIQ AI provides AI-powered baseball and softball pitch analysis, scoring, and custom training plan generation. The Service includes free pitch analysis, paid one-time training plans, and monthly subscription access to additional features.</p>

        <h2>3. Accounts and Eligibility</h2>
        <p>You must provide a valid email address to use the Service. If you are under 18, you must have permission from a parent or legal guardian. Parents or guardians are responsible for any use of the Service by minors.</p>

        <h2>4. Payments and Subscriptions</h2>
        <p>One-time plans are charged at the time of purchase and are non-refundable once the plan has been generated and delivered. Monthly subscriptions are billed on a recurring basis and can be cancelled at any time by contacting help@hit24.com. Cancellation takes effect at the end of the current billing period. All payments are processed securely through Stripe.</p>

        <h2>5. AI-Generated Content</h2>
        <p>Pitch scores, training plans, and coaching recommendations are generated by artificial intelligence. They are intended for informational and training purposes only. They do not constitute professional medical advice, physical therapy, or a substitute for in-person coaching. Use all training recommendations at your own risk.</p>

        <h2>6. Assumption of Risk</h2>
        <p>Baseball and softball training carries inherent physical risks. By using our training plans, you acknowledge that you participate in any exercises, drills, or activities at your own risk. We are not liable for any injuries that may occur. Always consult a physician before starting any new training program.</p>

        <h2>7. User Content</h2>
        <p>By uploading videos to the Service, you grant us a non-exclusive license to process and analyze those videos for the purpose of providing the Service. We do not store your original video files. We store extracted frame images temporarily for analysis purposes and pitch analysis results for your account history.</p>

        <h2>8. Intellectual Property</h2>
        <p>All content, features, and functionality of the Service are owned by HIT24. Generated training plans are licensed to you for personal, non-commercial use only. You may not resell, redistribute, or commercially exploit generated plans.</p>

        <h2>9. Prohibited Use</h2>
        <p>You may not: (a) use the Service for any unlawful purpose; (b) attempt to reverse engineer the Service; (c) upload content that is not a legitimate baseball or softball video; (d) create multiple accounts to circumvent usage limits; (e) share subscription access with others.</p>

        <h2>10. Limitation of Liability</h2>
        <p>To the maximum extent permitted by law, HIT24 shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.</p>

        <h2>11. Modifications</h2>
        <p>We reserve the right to modify these Terms at any time. Changes will be posted on this page with an updated date. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>

        <h2>12. Termination</h2>
        <p>We may suspend or terminate your access to the Service at any time for violation of these Terms or for any reason at our sole discretion.</p>

        <h2>13. Contact</h2>
        <p>For questions about these Terms, contact us at help@hit24.com.</p>
      </div>
    </div>
  );
}
